#!/usr/bin/env python

possibles = []

i = 265275
while i<= 781584:

    j = 0
    N = len(str(i))-1
    num = str(i)

    double = []
    
    while j < N:
        
        if num[j] > num[j+1]:
            break
        if num[j] == num[j+1]:
            double += [num[j], num[j+1]]
        j += 1
        
        M = len(double)
        if j == N and M > 1:
            if M == 8 or M == 6 or M == 4:
                if double[1] != double[2] or double[-2] != double[-3]:
                    possibles.append(i)
            elif M != 10:
                possibles.append(i)

    i += 1

print(possibles)
print()
print(len(possibles))
print()

