#!/usr/bin/env python


import os


path = os.path.abspath('.') 

tfuel = 0
tf_for_f = 0

def fuel_mass(fuel, f_for_f):

    fuel = fuel//3-2
    
    if (fuel) >= 0:
        f_for_f += fuel
        #print("fuel required to transport fuel : ", f_for_f)
        #print("fuel to compute the fuel for : ",fuel)
        return fuel_mass(fuel, f_for_f)
    else:
        return f_for_f


with open(path+'/input', 'r') as f:
    for l in f:
        fuel = int(l)//3-2
        f_for_f = fuel_mass(fuel, 0)
        print("Mass = {} Fuel = {}, fuel_for_fuel = {}".format(int(l), fuel, f_for_f))
        tfuel += fuel
        tf_for_f += f_for_f

print("Required fuel for the mass = ",tfuel)

print("Required fuel for the fuel= ",tf_for_f)

print("total fuel required = ", tfuel+tf_for_f)
