#!/usr/bin/env python

import os

path = os.path.abspath('.') 

def read_intcode(intcode):

    i = 0

    while i < len(intcode):
        if intcode[i] == 99:
            print(intcode[0])
            return intcode[0]
        elif intcode[i] == 1:
            intcode[intcode[i+3]] = intcode[intcode[i+1]] + intcode[intcode[i+2]] 
        elif intcode[i] == 2:   
            intcode[intcode[i+3]] = intcode[intcode[i+1]] * intcode[intcode[i+2]]
        i += 4
        

def bruteforce():
    
    verb = [v for v in range(100)]
    noon = [n for n in range(100)]
    
    k = [(n,v) for n in noon for v in verb]

    result = 0

    i = 0
    intcode = None
    
    while result != 19690720 and i < len(k):
        
        print(k[i])
        intcode = [1,0,0,3,1,1,2,3,1,3,4,3,1,5,0,3,2,13,1,19,1,5,19,23,2,10,23,27,1,27,5,31,2,9,31,35,1,35,5,39,2,6,39,43,1,43,5,47,2,47,10,51,2,51,6,55,1,5,55,59,2,10,59,63,1,63,6,67,2,67,6,71,1,71,5,75,1,13,75,79,1,6,79,83,2,83,13,87,1,87,6,91,1,10,91,95,1,95,9,99,2,99,13,103,1,103,6,107,2,107,6,111,1,111,2,115,1,115,13,0,99,2,0,14,0]
        intcode[1] = k[i][0]
        intcode[2] = k[i][1]
        print(intcode)
        result = read_intcode(intcode)
        i += 1
    print(intcode, result)

#test = [2,3,0,3,99]
#test = [1,9,10,3,2,3,11,0,99,30,40,50]
test = [2,4,4,5,99,0]


#read_intcode(intcode)
bruteforce()
