#!/usr/bin/env python

def fibo_rec(n):
    if n in memo:
        return memo[n]
    if n <= 2:
        f = 1
    else:
        f = fibo_rec(n-1) + fibo_rec(n-2)
        memo[n] = f
        print(f)
    return f

def fibo_bot(n):
    for k in range(1,n+1):
        if k <= 2:
            f = 1
            memo[k] = f
        else:
            f = memo[k-1] + memo[k-2]
            memo[k] = f
        print(memo,f)
    return memo[n]


if __name__ == '__main__':
    memo = {}
    #f = fibo_rec(4)
    f = fibo_bot(4) 


